#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GİB & UYAP Java Güvenlik Engeli (Exception Site List) Çözücü
Windows, macOS ve Linux üzerinde Java exception.sites yapılandırmasını yönetir.
"""

import os
import sys
import shutil
from datetime import datetime
from pathlib import Path

# Force UTF-8 stdout
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

OFFICIAL_SITES = [
    "https://ebildirge.sgk.gov.tr",
    "https://uyap.gov.tr",
    "https://avukat.uyap.gov.tr",
    "https://vatandas.uyap.gov.tr",
    "https://kurum.uyap.gov.tr",
    "https://bilirkisi.uyap.gov.tr",
    "https://uzlasmacilar.uyap.gov.tr",
    "https://icra.uyap.gov.tr",
    "https://portal.uyap.gov.tr",
    "https://intvd.gib.gov.tr",
    "https://ivd.gib.gov.tr",
    "https://dijital.gib.gov.tr",
    "https://edefter.gov.tr",
    "https://efatura.gov.tr",
    "https://earsiv.efatura.gov.tr",
    "https://mersis.gtb.gov.tr",
    "https://mersis.ticaret.gov.tr",
    "https://ekap.kik.gov.tr",
    "https://kamusm.bilgem.tubitak.gov.tr",
    "https://nes.kamusm.gov.tr",
    "https://giris.turkiye.gov.tr"
]

def get_java_security_path():
    """Java deployment security dizinini platforma göre belirler."""
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if not appdata:
            appdata = str(Path.home() / "AppData" / "Roaming")
        return Path(appdata) / "Sun" / "Java" / "Deployment" / "security"
    elif sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "Oracle" / "Java" / "Deployment" / "security"
    else:  # Linux / Unix
        return Path.home() / ".java" / "deployment" / "security"

def load_existing_sites(exception_file):
    if not exception_file.exists():
        return []
    try:
        with open(exception_file, "r", encoding="utf-8", errors="ignore") as f:
            lines = [line.strip() for line in f if line.strip() and not line.startswith("#")]
            return lines
    except Exception as e:
        print(f"[!] Dosya okuma hatası: {e}")
        return []

def apply_sites(target_dir=None, custom_sites=None):
    sec_dir = Path(target_dir) if target_dir else get_java_security_path()
    sec_dir.mkdir(parents=True, exist_ok=True)
    exception_file = sec_dir / "exception.sites"

    existing = load_existing_sites(exception_file)
    print(f"[*] Mevcut kayıtlı güvenli site sayısı: {len(existing)}")

    # Backup if exists
    if exception_file.exists():
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_file = sec_dir / f"exception.sites.bak_{timestamp}"
        shutil.copy2(exception_file, backup_file)
        print(f"[+] Yedek alındı: {backup_file.name}")

    sites_to_add = list(OFFICIAL_SITES)
    if custom_sites:
        sites_to_add.extend(custom_sites)

    merged = list(existing)
    added_count = 0
    for site in sites_to_add:
        cleaned = site.strip()
        if cleaned and cleaned not in merged:
            merged.append(cleaned)
            added_count += 1

    with open(exception_file, "w", encoding="utf-8") as f:
        f.write("# Java Exception Site List - Generated by gib-java-guvenlik-cozucu\n")
        f.write(f"# Updated: {datetime.now().isoformat()}\n")
        for s in merged:
            f.write(s + "\n")

    print(f"[✓] Tamamlandı! {added_count} yeni adres eklendi. Toplam liste: {len(merged)} site.")
    return added_count, len(merged)

def main():
    import argparse
    parser = argparse.ArgumentParser(description="GİB & UYAP Java Güvenlik Engeli Çözücü")
    parser.add_argument("--list", action="store_true", help="Mevcut güvenli siteleri listele")
    parser.add_argument("--add", nargs="+", help="Özel site veya URL'ler ekle")
    args = parser.parse_args()

    sec_dir = get_java_security_path()
    exception_file = sec_dir / "exception.sites"

    if args.list:
        sites = load_existing_sites(exception_file)
        print(f"--- Java Exception Sites ({exception_file}) ---")
        for s in sites:
            print(f" - {s}")
        print(f"Toplam: {len(sites)}")
        return

    apply_sites(custom_sites=args.add)

if __name__ == "__main__":
    main()
